db {
  dataSourceClassName = "org.postgresql.ds.PGSimpleDataSource"
  dataSource {
    serverName = "url"
    portNumber = port
    databaseName = "databasename"
    user = "username"
    password = "password"
  }
}

api {
  host: "url"
  threadSize: 4
  port: port
  timeoutSec: 100  #seconds
}